version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=AppiusDB
      - DATABASE_USER=AppiusDB
      - DATABASE_PASS=08092018acdc
      - DATABASE_URI=mongodb://mongodb:27017/AppiusDB
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: AppiusDB
      MONGO_INITDB_ROOT_PASSWORD: 08092018acdc
